# 1. NOMBRE DE LA APLICACI\u00d3N
spring.application.name=projecte_esport

# 2. CONFIGURACI\u00d3N DE MONGODB ATLAS
spring.data.mongodb.uri=URL MONGO
# Especificamos la base de datos expl\u00edcitamente para evitar confusiones
spring.data.mongodb.database=projecte_esport
spring.data.mongodb.auto-index-creation=true

# 3. SWAGGER / OPENAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# 4. CONFIGURACI\u00d3N DE FECHAS (Crucial para las reservas de Squash)
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
spring.jackson.time-zone=UTC

# 5. SEGURIDAD
logging.level.org.springframework.security=DEBUG